CREATE TABLE IF NOT EXISTS onchain_gem_candidates (
  chain_id VARCHAR(16) NOT NULL,
  symbol VARCHAR(128) NOT NULL,
  name VARCHAR(255) NULL,
  contract_address VARCHAR(255) NOT NULL,
  logo_url VARCHAR(1024) NULL,
  price DOUBLE NULL,
  market_cap DOUBLE NULL,
  liquidity DOUBLE NULL,
  volume DOUBLE NULL,
  price_change_percent DOUBLE NULL,
  holders BIGINT NULL,
  holders_top10_percent DOUBLE NULL,
  smart_money_inflow DOUBLE NULL,
  smart_money_traders INT NULL,
  smart_money_count INT NULL,
  token_risk_level INT NULL,
  launch_stage VARCHAR(32) NULL,
  direction VARCHAR(8) NULL,
  signal_status VARCHAR(32) NULL,
  wash_trading BOOLEAN NOT NULL DEFAULT FALSE,
  dev_sold_all BOOLEAN NOT NULL DEFAULT FALSE,
  score DOUBLE NOT NULL,
  status VARCHAR(32) NOT NULL,
  data_completeness VARCHAR(16) NOT NULL,
  sources JSON NOT NULL,
  evidence JSON NOT NULL,
  observed_at BIGINT NOT NULL,
  PRIMARY KEY (chain_id, contract_address),
  KEY idx_onchain_gem_score (score),
  KEY idx_onchain_gem_observed_at (observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
