CREATE TABLE IF NOT EXISTS futures_reference_factors (
  symbol VARCHAR(64) NOT NULL,
  interval_name VARCHAR(8) NOT NULL,
  candle_open_time BIGINT NOT NULL,
  provider VARCHAR(32) NOT NULL,
  signal_type VARCHAR(64) NOT NULL,
  signal_bias VARCHAR(16) NULL,
  status VARCHAR(32) NOT NULL,
  completeness VARCHAR(16) NOT NULL,
  score DOUBLE NOT NULL,
  confidence_adjustment DOUBLE NOT NULL,
  missing JSON NOT NULL,
  evidence JSON NOT NULL,
  aligned_spot_open_time BIGINT NULL,
  aligned_futures_open_time BIGINT NULL,
  spot_price_return DOUBLE NULL,
  futures_price_return DOUBLE NULL,
  spot_quote_volume_ratio DOUBLE NULL,
  futures_quote_volume_ratio DOUBLE NULL,
  oi_delta DOUBLE NULL,
  funding_rate DOUBLE NULL,
  basis DOUBLE NULL,
  price_gap DOUBLE NULL,
  observed_at BIGINT NOT NULL,
  PRIMARY KEY (symbol, interval_name, candle_open_time, provider),
  KEY idx_reference_factors_status_observed_at (status, observed_at),
  KEY idx_reference_factors_symbol_interval_candle (symbol, interval_name, candle_open_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
